labeler_input {
  event_id {
    publisher: "PUBLISHER_06"
    id: "EVENT_06"
    id_fingerprint: 12382229736359560625
  }
  timestamp_usec: 1626847100000006
  user_agent: "USER AGENT STRING EXAMPLE 06"
  geo {
    country_id: 106
    region_id: 100006
    city_id: 10000006
  }
  profile_info {
    email_user_info {
      user_id: "EMAIL_USER_06"
      profile_version: "20210706"
      demo {
        demo_bucket {
          gender: GENDER_MALE
          age {
            min_age: 21
            max_age: 30
          }
        }
        confidence: 0.6006
      }
      home_geo {
        country_id: 206
        region_id: 200006
        city_id: 20000006
      }
      creation_time_usec: 1626847100001006
      user_id_fingerprint: 12963008249086518371
    }
    phone_user_info {
      user_id: "PHONE_USER_06"
      profile_version: "20210706"
      demo {
        demo_bucket {
          gender: GENDER_FEMALE
          age {
            min_age: 31
            max_age: 40
          }
        }
        confidence: 0.7006
      }
      home_geo {
        country_id: 306
        region_id: 300006
        city_id: 30000006
      }
      creation_time_usec: 1626847100002006
      user_id_fingerprint: 12807464398485443195
    }
    proprietary_id_space_1_user_info {
      user_id: "PROPRIETARY_ID_SPACE_1_USER_06"
      profile_version: "20210706"
      demo {
        demo_bucket {
          gender: GENDER_UNKNOWN
          age {
            min_age: 41
            max_age: 1000
          }
        }
        confidence: 0.8006
      }
      home_geo {
        country_id: 406
        region_id: 400006
        city_id: 40000006
      }
      creation_time_usec: 1626847100003006
      user_id_fingerprint: 12807430737951419805
    }
  }
}
virtual_person_activities {
  virtual_person_id: 10000000000006
  label {
    demo {
      gender: GENDER_MALE
      age {
        min_age: 21
        max_age: 30
      }
    }
  }
}
virtual_person_activities {
  virtual_person_id: 20000000000006
  label {
    demo {
      gender: GENDER_FEMALE
      age {
        min_age: 31
        max_age: 40
      }
    }
  }
}
virtual_person_activities {
  virtual_person_id: 30000000000006
  label {
    demo {
      gender: GENDER_UNKNOWN
      age {
        min_age: 41
        max_age: 1000
      }
    }
  }
}
is_user_id_free_person: false
person_country_code: "COUNTRY_CODE_06"
person_region_code: "REGION_CODE_06"
acting_demo {
  gender: GENDER_MALE
  age {
    min_age: 21
    max_age: 30
  }
}
acting_demo_id_space: "email"
corrected_demo {
  gender: GENDER_FEMALE
  age {
    min_age: 31
    max_age: 40
  }
}
acting_fingerprint: 12963008249086518371
